INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (1581,'Westboro',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (1730,'Bedford',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (1833,'Georgetow',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (2116,'Boston',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (2139,'Cambridge',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (2184,'Braintree',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (2903,'Providence',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (3049,'Hollis',3);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (3801,'Portsmouth',3);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (6897,'Wilton',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (7960,'Morristown',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (8837,'Edison',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (10019,'New York',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (10038,'New York',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (11747,'Mellvile',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (14450,'Fairport',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (19428,'Philadelphia',3);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (19713,'Neward',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (20852,'Rockville',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (27403,'Greensboro',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (27511,'Cary',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (29202,'Columbia',4);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (30346,'Atlanta',4);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (31406,'Savannah',4);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (32859,'Orlando',4);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (33607,'Tampa',4);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (40222,'Louisville',1);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (44122,'Beachwood',3);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (45839,'Findlay',3);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (48075,'Southfield',3);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (48084,'Troy',3);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (48304,'Bloomfield Hills',3);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (53404,'Racine',3);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (55113,'Roseville',3);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (55439,'Minneapolis',3);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (60179,'Hoffman Estates',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (60601,'Chicago',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (72716,'Bentonville',4);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (75234,'Dallas',4);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (78759,'Austin',4);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (80202,'Denver',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (80909,'Colorado Springs',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (85014,'Phoenix',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (85251,'Scottsdale',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (90405,'Santa Monica',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (94025,'Menlo Park',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (94105,'San Francisco',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (95008,'Campbell',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (95054,'Santa Clara',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (95060,'Santa Cruz',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (98004,'Bellevue',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (98052,'Redmond',2);
INSERT INTO Territories (TerritoryId,TerritoryDescription,RegionId) VALUES (98104,'Seattle',2);